In [3]:
print('Week 10')

Week 10


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Linear Regression
from statsmodels.formula.api import ols

# KNN
from sklearn.neighbors import KNeighborsClassifier

# Train,Test,Spliot
from sklearn.model_selection import train_test_split

# Sklearn LinearRegression
from sklearn.linear_model import LinearRegression

# mean_squared_error
from sklearn.metrics import mean_squared_error

# cross_val_score and Kfold
from sklearn.model_selection import cross_val_score,KFold

# confusion
from sklearn.metrics import classification_report, confusion_matrix

#Imputation
from sklearn.impute import SimpleImputer\

# PipeLine
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

Precision is the number of true positive divided by number of all positive (true positive + false positive).

High precision means having lower false positive rate.

Not many legitimate are predicted to be fradulent.

Recall is the number of true positive divide by the sum of (true positive + false negative).

High recall means lower false negative rate.

Predicted most fradulent transcations correctly.

In [5]:
from sklearn.metrics import classification_report, confusion_matrix

churn_df = pd.read_csv('churn_df.csv',index_col=0)
churn_df.head()

account_length  total_day_charge  total_eve_charge  total_night_charge  \
0             101             45.85             17.65                9.64   
1              73             22.30              9.05                9.98   
2              86             24.62             17.53               11.49   
3              59             34.73             21.02                9.66   
4             129             27.42             18.75               10.11   

   total_intl_charge  customer_service_calls  churn  
0               1.22                       3      1  
1               2.75                       2      0  
2               3.13                       4      0  
3               3.24                       1      0  
4               2.59                       1      0

In [ ]:
# X = churn_df.drop('churn',axis=1).values
# y = churn_df['churn'].values

# print(X.shape)
# print(y.shape)

# knn = KNeighborsClassifier(n_neighbors=7)
# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4,random_state=42)
# knn.fit(X_train,y_train)
# y_pred = knn.predict(X_test)

# print(confusion_matrix(y_test,y_pred))
# print(classification_report(y_test,y_pred))

In [7]:
music = pd.read_csv('music.csv',index_col=0)
music.head()

popularity  acousticness  danceability  duration_ms  energy  \
0          41        0.6440         0.823     237000.0   0.814   
1          62        0.0855         0.686     154000.0   0.670   
2          42        0.2390         0.669     218000.0   0.736   
3          64        0.0125         0.522     246000.0   0.923   
4          60        0.1210         0.780     229000.0   0.467   

   instrumentalness  liveness  loudness  speechiness    tempo  valence  \
0          0.687000     0.117    -5.611        0.177  102.619    0.649   
1          0.000000     0.120    -7.626        0.225  173.915    0.636   
2          0.000169     0.598    -3.223        0.060  145.061    0.494   
3          0.017000     0.085    -4.560        0.054  120.406    0.595   
4          0.000134     0.314    -6.645        0.253   96.056    0.312   

        genre  
0        Jazz  
1         Rap  
2  Electronic  
3        Rock  
4         Rap

In [ ]:
music_dummies = pd.get_dummies(music['genre'],drop_first=True)
print(music_dummies)



     Anime  Blues  Classical  Country  Electronic  Hip-Hop   Jazz    Rap  \
0    False  False      False    False       False    False   True  False   
1    False  False      False    False       False    False  False   True   
2    False  False      False    False        True    False  False  False   
3    False  False      False    False       False    False  False  False   
4    False  False      False    False       False    False  False   True   
..     ...    ...        ...      ...         ...      ...    ...    ...   
995  False  False      False    False       False    False  False  False   
996  False  False      False    False        True    False  False  False   
997  False  False      False    False       False    False  False   True   
998  False  False      False    False       False    False  False  False   
999  False  False      False    False       False    False  False  False   

      Rock  
0    False  
1    False  
2    False  
3     True  
4    False  
..     ..

In [9]:
music_dummies = pd.concat([music,music_dummies],axis=1)
music_dummies = music_dummies.drop('genre',axis=1)
music_dummies.head()

popularity  acousticness  danceability  duration_ms  energy  \
0          41        0.6440         0.823     237000.0   0.814   
1          62        0.0855         0.686     154000.0   0.670   
2          42        0.2390         0.669     218000.0   0.736   
3          64        0.0125         0.522     246000.0   0.923   
4          60        0.1210         0.780     229000.0   0.467   

   instrumentalness  liveness  loudness  speechiness    tempo  valence  Anime  \
0          0.687000     0.117    -5.611        0.177  102.619    0.649  False   
1          0.000000     0.120    -7.626        0.225  173.915    0.636  False   
2          0.000169     0.598    -3.223        0.060  145.061    0.494  False   
3          0.017000     0.085    -4.560        0.054  120.406    0.595  False   
4          0.000134     0.314    -6.645        0.253   96.056    0.312  False   

   Blues  Classical  Country  Electronic  Hip-Hop   Jazz    Rap   Rock  
0  False      False    False       False    False   True  False  False  
1  False      False    False       False    False  False   True  False  
2  False      False    False        True    False  False  False  False  
3  False      False    False       False    False  False  False   True  
4  False      False    False       False    False  False   True  False

In [10]:
from sklearn.model_selection import cross_val_score,KFold
from sklearn.linear_model import LinearRegression

X = music_dummies.drop('popularity',axis=1).values
y = music_dummies['popularity'].values

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
kf = KFold(n_splits=5,shuffle=True,random_state=42)
reg = LinearRegression()

reg_cv = cross_val_score(reg,X_train,y_train,cv=kf,scoring='neg_mean_squared_error')

print(np.sqrt(-reg_cv))

[8.15810501 8.63114581 7.52281687 8.62016985 7.91296943]


In [28]:
music_df = pd.read_csv('music_unclean.csv',index_col=0)
music_df.isna().sum().sort_values()

genre                 8
popularity           31
loudness             44
liveness             46
tempo                46
speechiness          59
duration_ms          91
instrumentalness     91
danceability        143
valence             143
acousticness        200
energy              200
dtype: int64

In [29]:
music_df = music_df.dropna(subset=['genre','popularity','loudness','liveness','tempo'])
music_df.isna().sum().sort_values()

popularity            0
liveness              0
loudness              0
tempo                 0
genre                 0
duration_ms          29
instrumentalness     29
speechiness          53
danceability        127
valence             127
acousticness        178
energy              178
dtype: int64

In [30]:
from sklearn.impute import SimpleImputer


# change encoding of genre as boolean based around Rock
music_df["genre"] = np.where(music_df["genre"] == "Rock",1,0)

# n x 1 matrix of catergorial values X
X_cat = music_df["genre"].values.reshape(-1, 1)
X_num = music_df.drop (["genre", "popularity"], axis=1).values
y = music_df["popularity"].values

X_train_cat, X_test_cat, y_train, y_test = train_test_split(X_cat, y, test_size=0.2,random_state=12)
X_train_num, X_test_num, y_train, y_test = train_test_split(X_num, y, test_size=0.2,random_state=12)

imp_cat = SimpleImputer(strategy="most_frequent")
X_train_cat = imp_cat.fit_transform(X_train_cat)
X_test_cat = imp_cat.transform(X_test_cat)

imp_num = SimpleImputer() # default; mean
X_train_num = imp_num.fit_transform(X_train_num)
X_test_num = imp_num. transform(X_test_num)

# join two matrixes column wise
X_train = np.append(X_train_num, X_train_cat, axis=1)
X_test = np.append(X_test_num, X_test_cat, axis=1)


knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
print(knn.score(X_test,y_test))

0.0111731843575419


In [31]:
music_df.head()

popularity  acousticness  danceability  duration_ms  energy  \
1        31.0       0.73900         0.565     261000.0   0.393   
2        57.0       0.00879         0.433     263000.0   0.815   
3        63.0       0.01050         0.359     564000.0   0.762   
5        65.0           NaN         0.491         -1.0     NaN   
6        44.0       0.71000         0.627          NaN   0.496   

   instrumentalness  liveness  loudness  speechiness    tempo  valence  genre  
1          0.000845     0.143    -9.309        0.024   75.537    0.229      0  
2          0.000000     0.138    -3.658          NaN  125.358    0.461      1  
3          0.281000     0.368    -8.323        0.032   89.259    0.167      1  
5          0.000003     0.626    -6.564        0.028  112.704    0.407      1  
6               NaN     0.343   -11.866        0.040   95.000    0.080      0

In [45]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

music_df = pd.read_csv('music_unclean.csv',index_col=0)
music_df = music_df.dropna(subset=['genre','popularity','loudness','liveness','tempo'])
music_df['genre'] = np.where(music_df['genre'] == 'Rock', 1, 0)

X = music_df.drop('genre', axis = 1).values
y = music_df['genre'].values

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

steps = [('imputation', SimpleImputer()),
         ('Log_reg', LogisticRegression(max_iter = 100000))]

pipeline = Pipeline(steps)
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
print(pipeline.score(X_test, y_test))
print(confusion_matrix(y_pred,y_test))

0.835820895522388
[[104  13]
 [ 31 120]]


In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
music_df = pd.read_csv('music_unclean.csv', index_col = 0)
music_df = music_df.dropna(subset=['genre','popularity','loudness','liveness','tempo'])
music_df['genre'] = np.where(music_df['genre'] == 'Rock', 1, 0)
X = music_df.drop('genre', axis = 1).values
y = music_df['genre'].values
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

steps = [('imputation', SimpleImputer()),
         ('Log_reg', LogisticRegression(max_iter = 100000))]

pipeline = Pipeline(steps)
pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(pipeline.score(X_test,y_test)) 

[[104  31]
 [ 13 120]]
0.835820895522388


In [60]:
music_df = pd.read_csv('music_unclean.csv',index_col=0)
music_df = music_df.dropna(subset=['genre','popularity','loudness','liveness','tempo'])
music_df['genre'] = np.where(music_df['genre'] == 'Rock', 1, 0)

X = music_df.drop('genre',axis=1).values
y = music_df['genre'].values

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

imputer = SimpleImputer()

knn = KNeighborsClassifier(n_neighbors=3)

steps = [('imputation',SimpleImputer()),
         ('knn',KNeighborsClassifier(n_neighbors=3))]

pipeline = Pipeline(steps=steps)

pipeline.fit(X_train,y_train)

y_pred = pipeline.predict(X_test)
print(pipeline.score(X_test,y_test))
print(confusion_matrix(y_true=y_test,y_pred=y_pred))

0.582089552238806
[[78 57]
 [55 78]]


In [59]:
music_df = pd.read_csv('music_unclean.csv',index_col=0)
music_df = music_df.dropna(subset=['genre','popularity','loudness','liveness','tempo'])
music_df['genre'] = np.where(music_df['genre'] == 'Rock', 1, 0)

X = music_df.drop('genre',axis=1).values
y = music_df['genre'].values

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

imputer = SimpleImputer()
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train,y_train)
print(knn.score(X_test,y_test))
y_pred = knn.predict(X_train)

0.582089552238806
