In [33]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score, KFold
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [16]:
# churn_df = pd.read_csv('churn_df.csv')
# X = churn_df.drop('churn',axis = 1).values
# y = churn_df['churn'].values
# knn = KNeighborsClassifier(n_neighbors=7)
# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.4,random_state=42)

# knn.fit(X_train,y_train)
# y_pred = knn.predict(X_test)

# print(confusion_matrix(y_test,y_pred))
# print(classification_report(y_test,y_pred))

In [17]:
music = pd.read_csv('music.csv')
print(music.info())
print(music.head(10))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Unnamed: 0        1000 non-null   int64  
 1   popularity        1000 non-null   int64  
 2   acousticness      1000 non-null   float64
 3   danceability      1000 non-null   float64
 4   duration_ms       1000 non-null   float64
 5   energy            1000 non-null   float64
 6   instrumentalness  1000 non-null   float64
 7   liveness          1000 non-null   float64
 8   loudness          1000 non-null   float64
 9   speechiness       1000 non-null   float64
 10  tempo             1000 non-null   float64
 11  valence           1000 non-null   float64
 12  genre             1000 non-null   object 
dtypes: float64(10), int64(2), object(1)
memory usage: 101.7+ KB
None
   Unnamed: 0  popularity  acousticness  danceability  duration_ms  energy  \
0           0          41        0.6440  

In [18]:
music_dummies = pd.get_dummies(music['genre'],drop_first=True)
music_dummies.head()

Anime  Blues  Classical  Country  Electronic  Hip-Hop   Jazz    Rap   Rock
0  False  False      False    False       False    False   True  False  False
1  False  False      False    False       False    False  False   True  False
2  False  False      False    False        True    False  False  False  False
3  False  False      False    False       False    False  False  False   True
4  False  False      False    False       False    False  False   True  False

In [19]:
music_dummies = pd.concat([music,music_dummies],axis=1)
music_dummies = music_dummies.drop('genre',axis=1)

music_dummies.head()

Unnamed: 0  popularity  acousticness  danceability  duration_ms  energy  \
0           0          41        0.6440         0.823     237000.0   0.814   
1           1          62        0.0855         0.686     154000.0   0.670   
2           2          42        0.2390         0.669     218000.0   0.736   
3           3          64        0.0125         0.522     246000.0   0.923   
4           4          60        0.1210         0.780     229000.0   0.467   

   instrumentalness  liveness  loudness  speechiness  ...  valence  Anime  \
0          0.687000     0.117    -5.611        0.177  ...    0.649  False   
1          0.000000     0.120    -7.626        0.225  ...    0.636  False   
2          0.000169     0.598    -3.223        0.060  ...    0.494  False   
3          0.017000     0.085    -4.560        0.054  ...    0.595  False   
4          0.000134     0.314    -6.645        0.253  ...    0.312  False   

   Blues  Classical  Country  Electronic  Hip-Hop   Jazz    Rap   Rock  
0  False      False    False       False    False   True  False  False  
1  False      False    False       False    False  False   True  False  
2  False      False    False        True    False  False  False  False  
3  False      False    False       False    False  False  False   True  
4  False      False    False       False    False  False   True  False  

[5 rows x 21 columns]

In [28]:
# X = music_dummies.drop('popularity',axis=1).values
# y = music_dummies['popularity'].values
# X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
# kf = KFold(n_splits=5,shuffle=True,random_state=42)
# linreg = LinearRegression()
# linreg_cv = cross_val_score(linreg,X_train,y_train,cv=kf,scoring='neg_mean_squared_error')
# print(np.sqrt(-linreg_cv))

In [24]:
music_unclean = pd.read_csv('music_unclean.csv',index_col=0)
print(music_unclean.isna().sum().sort_values())

genre                 8
popularity           31
loudness             44
liveness             46
tempo                46
speechiness          59
duration_ms          91
instrumentalness     91
danceability        143
valence             143
acousticness        200
energy              200
dtype: int64


In [30]:
music_unclean = music_unclean.dropna(subset=['genre','popularity','loudness','liveness','tempo'])
music_unclean['genre'] = np.where(music_unclean['genre'] == 'Rock',1,0)
print(music_unclean.isna().sum().sort_values())

popularity            0
liveness              0
loudness              0
tempo                 0
genre                 0
duration_ms          29
instrumentalness     29
speechiness          53
danceability        127
valence             127
acousticness        178
energy              178
dtype: int64


In [47]:
# X_cat = music_unclean['genre'].values.reshape(-1,1)
# X_num = music_unclean.drop(['genre','popularity'],axis=1).values
# y = music_unclean['popularity'].values
# X_train_cat,X_test_cat,y_train,y_test = train_test_split(X_cat,y,test_size=0.2,random_state=12)
# X_train_num,X_test_num,y_train,y_test = train_test_split(X_num,y,test_size=0.2,random_state=12)

# imp_cat = SimpleImputer(strategy='most_frequent')
# X_train_cat = imp_cat.fit_transform(X_train_cat)
# X_test_cat = imp_cat.fit_transform(X_test_cat)

# imp_num = SimpleImputer()
# X_train_num = imp_num.fit_transform(X_train_num)
# X_test_num = imp_num.fit_transform(X_test_num)

# X_train = np.append(X_train_num,X_train_cat,axis=1)
# X_test = np.append(X_test_num,X_test_cat,axis=1)

# knn = KNeighborsClassifier(n_neighbors=5)
# knn.fit(X_train,y_train)
# y_pred = knn.predict(X_test)
# print(knn.score(X_test,y_test))

In [32]:
# from sklearn.pipeline import Pipeline
# from sklearn.linear_model import LogisticRegression
# music_df = pd.read_csv('music_unclean.csv', index_col = 0)
# music_df = music_df.dropna(subset=['genre','popularity','loudness','liveness','tempo'])
# music_df['genre'] = np.where(music_df['genre'] == 'Rock', 1, 0)
# X = music_df.drop('genre', axis = 1).values
# y = music_df['genre'].values
# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

# steps = [('imputation', SimpleImputer()),
#          ('Log_reg', LogisticRegression(max_iter = 100000))]

# pipeline = Pipeline(steps)
# pipeline.fit(X_train, y_train)

# y_pred = pipeline.predict(X_test)
# print(confusion_matrix(y_test, y_pred))
# print(pipeline.score(X_test,y_test))

[[104  31]
 [ 13 120]]
0.835820895522388


In [54]:
music_df = pd.read_csv('music_unclean.csv',index_col=0)
print(music_df.isna().sum().sort_values())

genre                 8
popularity           31
loudness             44
liveness             46
tempo                46
speechiness          59
duration_ms          91
instrumentalness     91
danceability        143
valence             143
acousticness        200
energy              200
dtype: int64


In [55]:
music_df = music_df.dropna(subset=['genre','popularity','loudness','liveness','tempo'])
print(music_df.isna().sum().sort_values())

popularity            0
liveness              0
loudness              0
tempo                 0
genre                 0
duration_ms          29
instrumentalness     29
speechiness          53
danceability        127
valence             127
acousticness        178
energy              178
dtype: int64


In [62]:
# music_df = pd.read_csv('music_unclean.csv',index_col=0)
# #print(music_df.isna().sum().sort_values())

# music_df = music_df.dropna(subset=['genre','popularity','loudness','liveness','tempo'])
# #print(music_df.isna().sum().sort_values())

# music_df['genre'] = np.where(music_df['genre'] == "Rock" ,1,0)
# X = music_df.drop('genre',axis=1).values
# y = music_df['genre'].values

# X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.3,random_state=42)

# imputer = SimpleImputer()

# knn = KNeighborsClassifier(n_neighbors=7)

# steps = [
#     ("imputer",imputer),
#     ("knn",knn)
# ]

# pipeline = Pipeline(steps)
# pipeline.fit(X_train,y_train)
# y_predict = pipeline.predict(X_test)

# print(confusion_matrix(y_test,y_predict))
# print(pipeline.score(X_test,y_test))

[[179 128]
 [143 175]]
0.5664


In [78]:
# music_df = pd.read_csv('music_unclean.csv', index_col = 0)
# #print(music_df.isna().sum().sort_values())

# music_df = music_df.dropna(subset=["genre", "popularity", "loudness", "liveness", "tempo"])

# print(music_df.isna().sum().sort_values())
# print("Shape of the `music_df`: {}".format(music_df.shape))

# # Convert genre to a binary feature
# music_df["genre"] = np.where(music_df["genre"] == "Rock", 1, 0)

# X = music_df.drop('genre', axis = 1).values
# y = music_df['genre'].values

# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
# # Instantiate an imputer
# imputer = SimpleImputer()
# X_train = imputer.fit_transform(X_train) ###################
# X_test = imputer.transform(X_test)          ###################

# # Instantiate a knn model
# knn = KNeighborsClassifier(n_neighbors=7)

# # Build steps for the pipeline
# steps = [("imputer", imputer), 
#          ("knn", knn)]

# # Create the pipeline
# pipeline = Pipeline(steps)

# # Fit the pipeline to the training data
# pipeline.fit(X_train, y_train)

# # Make predictions on the test set
# y_pred = pipeline.predict(X_test)

# # Print the confusion matrix

# print(confusion_matrix(y_test, y_pred))
# print(pipeline.score(X_test,y_test))


popularity            0
liveness              0
loudness              0
tempo                 0
genre                 0
duration_ms          29
instrumentalness     29
speechiness          53
danceability        127
valence             127
acousticness        178
energy              178
dtype: int64
Shape of the `music_df`: (892, 12)
[[55 39]
 [34 51]]
0.5921787709497207


In [94]:
music_df = pd.read_csv('music_unclean.csv', index_col = 0)
#print(music_df.isna().sum().sort_values())

music_df = music_df.dropna(subset=["genre", "popularity", "loudness", "liveness", "tempo"])

print(music_df.isna().sum().sort_values())

# Convert genre to a binary feature
music_df["genre"] = np.where(music_df["genre"] == "Rock", 1, 0)

X = music_df.drop('genre', axis = 1).values
y = music_df['genre'].values

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=42)

imp = SimpleImputer(strategy='mean')
X_train = imp.fit_transform(X_train)
X_test = imp.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
y_predict = knn.predict(X_test)
#print(con)
print(knn.score(X_test,y_test))

popularity            0
liveness              0
loudness              0
tempo                 0
genre                 0
duration_ms          29
instrumentalness     29
speechiness          53
danceability        127
valence             127
acousticness        178
energy              178
dtype: int64
0.6143497757847534
